### PR TITLE
Avoid overflow

### PR DESCRIPTION
**Pull request by ball-hayden**
Prevents overflows in `offset` leading to arithmetic errors.

~Also corrects the `swift_versions` definition - `5.x` is not a valid version.~

### CODE REVIEW

**Comment by ball-hayden** [comment]
@philips77 would you consider reviewing this PR, please?

**Comment by philips77** [comment]
Hi, why are you afraid of an overflow with UInt? Assuming malicious reply from the device, as cbor allows 64-bit values?

**Comment by ball-hayden** [comment]
Not afraid of - actively seeing arithmetic errors when uploading upgrades (I forget the exact error message now).

I'm not sure I can fully explain this, but being consistent with UInt64 throughout (rather than casting through various integer types) makes the error go away.

**Comment by philips77** [comment]
Thanks. Me and @dinesharjani will look into it.

**Comment by dinesharjani** [comment]
@ball-hayden hi, thanks for the PR.

Can you fix the branch so it's ahead of the current master branch / 1.1 release? We can merge your fix then.

**Comment by ball-hayden** [comment]
Rebased now @dinesharjani - thanks.

**Comment by philips77** [comment]
> I'm not sure I can fully explain this, but being consistent with `UInt64` throughout (rather than casting through `UInt32`) makes the error go away.

`UInt` type is 32-bit long, so allows up to 4 GB. The `Data.count` is actually `Int`, so up to 2 GB. How is it possible that you're getting an overflow. Do you remember where was it?
Perhaps changing to `UInt64` does not remove the root cause, but rather hides it, or would also crash, but with different values?

As`Data.count` is of type `Int`, perhaps it may be better to change to `Int` instead?
The `offset` returned from the device may, however, be sent as 64-bit value (in CBOR message).

**Pull request merged**
